name: chatapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.3
  cloud_firestore: 5.5.0
  firebase_core: 3.8.0
  provider: ^6.1.2
  google_sign_in: ^6.2.2
  animate_do: ^3.3.4
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
